![NYC Skyline](img/nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, you will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx` (Excel files).

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [87]:
# We've loaded the necessary packages for you in the first cell. Please feel free to add as many cells as you like!
suppressMessages(library(dplyr)) # This line is required to check your answer correctly
options(readr.show_types = FALSE) # This line is required to check your answer correctly
library(readr)
library(readxl)
library(stringr)
library(tibble)
# Begin coding here ...
#load the files

airbnb_price <- read.csv("data/airbnb_price.csv")
airbnb_room_type <- read_excel("data/airbnb_room_type.xlsx")
airbnb_last_review <- read_tsv("data/airbnb_last_review.tsv", show_col_types = FALSE)

In [88]:
#merge the tree files into one data frame

df_airbnb <- airbnb_price %>%
			inner_join(airbnb_room_type, by = "listing_id") %>%
			inner_join(airbnb_last_review, by = "listing_id")

head(df_airbnb)

  listing_id price       nbhood_full
1 2595       225 dollars Manhattan, Midtown
2 3831       89 dollars  Brooklyn, Clinton Hill
3 5099       200 dollars Manhattan, Murray Hill
4 5178       79 dollars  Manhattan, Hell's Kitchen
5 5238       150 dollars Manhattan, Chinatown
6 5295       135 dollars Manhattan, Upper West Side
  description                               room_type       host_name
1 Skylit Midtown Castle                     Entire home/apt Jennifer
2 Cozy Entire Floor of Brownstone           Entire home/apt LisaRoxanne
3 Large Cozy 1 BR Apartment In Midtown East Entire home/apt Chris
4 Large Furnished Room Near B'way           private room    Shunichi
5 Cute & Cozy Lower East Side 1 bdrm        Entire home/apt Ben
6 Beautiful 1br on Upper West Side          Entire home/apt Lena
  last_review
1 May 21 2019
2 July 05 2019
3 June 22 2019
4 June 24 2019
5 June 09 2019
6 June 22 2019

In [89]:
#Find the earliest and last reviews
#Creare new column of last_review changing the to the date type format
df_airbnb <- df_airbnb %>%
		mutate(date_last_review = as.Date(last_review, format = "%B %d %Y"))
head(df_airbnb)
#Find the dates which are required

aerliest_last_reviews <- new_df %>%
						summarize(earliest_review = min(date_last_review), last_review = max(date_last_review))

print(aerliest_last_reviews)

  listing_id price       nbhood_full
1 2595       225 dollars Manhattan, Midtown
2 3831       89 dollars  Brooklyn, Clinton Hill
3 5099       200 dollars Manhattan, Murray Hill
4 5178       79 dollars  Manhattan, Hell's Kitchen
5 5238       150 dollars Manhattan, Chinatown
6 5295       135 dollars Manhattan, Upper West Side
  description                               room_type       host_name
1 Skylit Midtown Castle                     Entire home/apt Jennifer
2 Cozy Entire Floor of Brownstone           Entire home/apt LisaRoxanne
3 Large Cozy 1 BR Apartment In Midtown East Entire home/apt Chris
4 Large Furnished Room Near B'way           private room    Shunichi
5 Cute & Cozy Lower East Side 1 bdrm        Entire home/apt Ben
6 Beautiful 1br on Upper West Side          Entire home/apt Lena
  last_review  date_last_review
1 May 21 2019  2019-05-21
2 July 05 2019 2019-07-05
3 June 22 2019 2019-06-22
4 June 24 2019 2019-06-24
5 June 09 2019 2019-06-09
6 June 22 2019 2019-06-22

  earliest_review last_review
1      2019-01-01  2019-07-09

In [90]:
#Change the room_type into upper case letter
df_airbnb$room_type <- str_to_upper(df_airbnb$room_type)
#Count the number of private rooms
num_private_rooms <- df_airbnb %>%
					filter(room_type == "PRIVATE ROOM") %>%
					count(room_type)

num_private_rooms

  room_type    n
1 PRIVATE ROOM 11356

In [91]:
#Average listing price for all rooms
#Remove the "dollar" string from the price column
df_airbnb$price <- str_remove(df_airbnb$price, "dollars")

#transform the price column into numeric
df_airbnb$price <- as.numeric(df_airbnb$price)

head(df_airbnb)

#average price

avg_price <- df_airbnb %>%
			summarize(avg_price = round(mean(price), 2))
print(avg_price)

  listing_id price nbhood_full
1 2595       225   Manhattan, Midtown
2 3831        89   Brooklyn, Clinton Hill
3 5099       200   Manhattan, Murray Hill
4 5178        79   Manhattan, Hell's Kitchen
5 5238       150   Manhattan, Chinatown
6 5295       135   Manhattan, Upper West Side
  description                               room_type       host_name
1 Skylit Midtown Castle                     ENTIRE HOME/APT Jennifer
2 Cozy Entire Floor of Brownstone           ENTIRE HOME/APT LisaRoxanne
3 Large Cozy 1 BR Apartment In Midtown East ENTIRE HOME/APT Chris
4 Large Furnished Room Near B'way           PRIVATE ROOM    Shunichi
5 Cute & Cozy Lower East Side 1 bdrm        ENTIRE HOME/APT Ben
6 Beautiful 1br on Upper West Side          ENTIRE HOME/APT Lena
  last_review  date_last_review
1 May 21 2019  2019-05-21
2 July 05 2019 2019-07-05
3 June 22 2019 2019-06-22
4 June 24 2019 2019-06-24
5 June 09 2019 2019-06-09
6 June 22 2019 2019-06-22

  avg_price
1    141.78

In [92]:
#lets join all outcomes into a table
review_dates <- tibble(
	first_reviewed = aerliest_last_reviews$earliest_review,
	last_reviewed = aerliest_last_reviews$last_review,
	nb_private_rooms = num_private_rooms$n,
	avg_price = avg_price$avg_price
)

review_date

  first_reviewed last_reviewed nb_private_rooms avg_price
1 2019-01-01     2019-07-09    2248             141.8